;; What follows is a "manifest" equivalent to the command line you gave.
;; You can store it in a file that you may then pass to any 'guix' command
;; that accepts a '--manifest' (or '-m') option.

(specifications->manifest
  (list "nss-certs"
        "bash"
        "coreutils"
        "curl"
        "grep"
        "sed"
        "gawk"
        "make"
        "cmake"
        "findutils"
        "libgccjit"
        "gmp"
        "openssl"
        "gcc-toolchain:static"
        "gcc-toolchain"
        "glibc-locales"
        "pkg-config"
        "clang"
        "ncurses"
        "ncurses-with-tinfo"
        "neovim"
        "tmux"
        "openssl:static"
        "sqlite"
        "valgrind"
        "gdb"
        "openssh"
        "git"
        "util-linux"
        "htop"
        "wget"
        "procps"
        "less"
        "tar"
        "gzip"
        "xz"))
