(custom-set-variables
 '(custom-enabled-themes '(tango-dark))
 '(default-input-method "chinese-tonepy-punct")
 '(fido-vertical-mode t)
 '(inhibit-startup-screen t)
 '(menu-bar-mode nil)
 '(scroll-bar-mode nil)
 '(tool-bar-mode nil)
 '(treesit-font-lock-level 4))
(setq auto-mode-alist
      (append '(("\\.rs\\'" . rust-ts-mode))
              auto-mode-alist))
(setq major-mode-remap-alist
      '((sh-mode . bash-ts-mode)
	(js-json-mode . json-ts-mode)
	(python-mode . python-ts-mode)
	(conf-toml-mode . toml-ts-mode)
	(c-mode . c-ts-mode)
	(c++-mode . c++-ts-mode)
	(c-or-c++-mode . c-or-c++-ts-mode)))
(set-fontset-font t 'cjk-misc "Noto Sans CJK SC")
(set-fontset-font t 'han "Noto Sans CJK SC")
(set-fontset-font t 'kana "Noto Sans CJK JP")
(set-fontset-font t 'hangul "Noto Sans CJK KR")
(set-fontset-font t 'balinese "Noto Sans Balinese")
(custom-set-faces
 '(default ((t (:family "Noto Sans Mono")))))
