(defun tetris ())
(setq default-input-method "chinese-tonepy-punct")
(setq inhibit-startup-screen t)
(pixel-scroll-precision-mode)
(global-display-line-numbers-mode 1)
(load-theme 'tsdh-light)
(tool-bar-mode -1)
(custom-set-variables
 '(treesit-font-lock-level 4))
(setq eglot-ignored-server-capabilities '(:inlayHintProvider :hoverProvider))
