(defun tetris ())
(setq default-input-method "chinese-tonepy-punct")
(setq inhibit-startup-screen t)
(pixel-scroll-precision-mode)
(global-display-line-numbers-mode 1)
(setq treesit-extra-load-path '("~/.guix-home/profile/lib/tree-sitter/"))
