music_directory		"~/.mpd/音乐"
playlist_directory	"~/.mpd/playlists"
db_file			"~/.mpd/database"
pid_file		"~/.mpd/pid"
bind_to_address		"127.0.0.1"
#bind_to_address	"~/.mpd/socket"
port			"6600"
auto_update		"yes"
#audio_output {
#	     type	"pipewire"
#	     name	"PipeWire Sound Server"
#}
audio_output {
	     type "pulse"
	     name "My Pulse Output"
}

